version: '3.8'
services:
  mysql:
    image: mysql:8.0
    env_file:
      - ./.env
    volumes:
      - /mysql_data:/var/lib/mysql
    container_name: mysql-container

  onbuyway-node:
    image: kevin71336099/onbuyway-node
    env_file:
      - ./.env
    ports:
      - '80:80'
    container_name: onbuyway-node
