version: '3.8'
services:
  db:
    image: postgres:16
    env_file:
      - ./.env
    volumes:
      - /postgresql_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    container_name: postgres-container
    networks:
      - app-network

  onbuyway-node:
    depends_on:
      - db
    image: kevin71336099/onbuyway-node
    env_file:
      - ./.env
    environment:
      NODE_ENV: production
    ports:
      - '80:80'
    container_name: onbuyway-node
    networks:
      - app-network

volumes:
  postgresql_data:

networks:
  app-network:
    driver: bridge
