version: '3.8'
services:
  mysql:
    image: mysql:8.0
    env_file:
      - ./.env
    ports:
      - '3306:3306'
    volumes:
      - /mysql_data:/var/lib/mysql
    container_name: mysql-container

  onbuyway-node:
    depends_on:
      - mysql
    image: kevin71336099/onbuyway-node
    env_file:
      - ./.env
    environment:
      MYSQL_HOST: mysql
    ports:
      - '80:80'
    container_name: onbuyway-node

volumes:
  mysql_data:
