name: onBuyWay Project CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    env:
      IMGUR_CLIENT_ID: ${{ secrets.IMGUR_CLIENT_ID }}
      IMGUR_CLIENT_SECRET: ${{ secrets.IMGUR_CLIENT_SECRET }}
      IMGUR_REFRESH_TOKEN: ${{ secrets.IMGUR_REFRESH_TOKEN }}
      IMGUR_ALBUM_ID: ${{ secrets.IMGUR_ALBUM_ID }}
      GMAIL_USER: ${{ secrets.GMAIL_USER }}
      GMAIL_PASS: ${{ secrets.GMAIL_PASS }}
      URL: ${{ secrets.URL }}
      HASH_KEY: ${{ secrets.HASH_KEY }}
      HASH_IV: ${{ secrets.HASH_IV }}
      MERCHANT_ID: ${{ secrets.MERCHANT_ID }}

    strategy:
      matrix:
        node-version: ['18.19.0']
        mysql-version: ['8.0']
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: ${{ secrets.MYSQL_TEST_DB }}
          MYSQL_USER: ${{secrets.MYSQL_TEST_USER}}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_TEST_PASSWORD }}
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_TEST_PASSWORD }}
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js version ${{matrix.node-version}}
        uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node-version}}
      - name: Install node modules
        run: npm install
      - name: Database migrate
        run: npx sequelize db:migrate --env test
      - name: Debug
        run: |
          mysql --host=127.0.0.1 --user=${{secrets.MYSQL_TEST_USER}} --password=${{ secrets.MYSQL_TEST_PASSWORD }} ${{ secrets.MYSQL_TEST_DB }} <<MY_QUERY
          SHOW GRANTS;
          MY_QUERY
      - name: Jest API tests
        run: npm run test
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push onbuyway image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/onbuyway-node:latest
