name: onBuyWay Project CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    env:
      IMGUR_CLIENT_ID: ${{ secrets.IMGUR_CLIENT_ID }}
      IMGUR_CLIENT_SECRET: ${{ secrets.IMGUR_CLIENT_SECRET }}
      IMGUR_REFRESH_TOKEN: ${{ secrets.IMGUR_REFRESH_TOKEN }}
      IMGUR_ALBUM_ID: ${{ secrets.IMGUR_ALBUM_ID }}
      GMAIL_USER: ${{ secrets.GMAIL_USER }}
      GMAIL_PASS: ${{ secrets.GMAIL_PASS }}
      URL: ${{ secrets.URL }}
      HASH_KEY: ${{ secrets.HASH_KEY }}
      HASH_IV: ${{ secrets.HASH_IV }}
      MERCHANT_ID: ${{ secrets.MERCHANT_ID }}
      MYSQL_ROOT_PASSWORD: ${{secrets.MYSQL_ROOT_PASSWORD}}
      MYSQL_DB: ${{secrets.MYSQL_DB}}
      MYSQL_USER: ${{secrets.MYSQL_USER}}
      MYSQL_PASSWORD: ${{secrets.MYSQL_PASSWORD}}

    strategy:
      matrix:
        node-version: ['18.19.0']
        mysql-version: ['8.0']
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: ${{ env.MYSQL_ROOT_PASSWORD }}
          MYSQL_DATABASE: ${{ env.MYSQL_DB }}
          MYSQL_USER: ${{ env.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ env.MYSQL_PASSWORD }}
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js version ${{matrix.node-version}}
        uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node-version}}
      - name: Shutdown the Default MySQL
        run: sudo service mysql stop
      - name: Install node modules
        run: npm install
      - name: Database migrate
        run: npx sequelize db:migrate --env test
      - name: Jest API tests
        run: npm run test
