name: onBuyWay Project CD
on:
  workflow_run:
    workflows: ['onBuyWay Project CI']
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # SSH Remote Commands
      - name: Executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker stop postgres-container onbuyway-node
            docker rm postgres-container onbuyway-node
            docker rmi kevin71336099/onbuyway-node:latest
            sudo wget -O docker-compose.yml https://raw.githubusercontent.com/onBuyWay/Backend/main/docker-compose.yml
            docker-compose pull
            docker-compose up -d --build
            docker-compose run --name migrate-container onbuyway-node npx sequelize db:migrate
            docker rm migrate-container
